spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    notification:
      username: ${NOTIFICATION_EMAIL}
      password: ${NOTIFICATION_EMAIL_PASSWORD}
    user:
      username: aaa
      password: bbb
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          host: smtp.gmail.com
          port: 587
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory