spring:
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
