#!/bin/bash
set -e

psql <<-EOSQL
	CREATE DATABASE $DATABASE_NAME;
	CREATE USER $DATABASE_USERNAME;
	ALTER USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
EOSQL
